### ISSUE TITLE
demo跑不起来

### ISSUE THREAD

**Issue by 1977474741** [UncAnnyZ/MiniProgram-HotUpdate#1]
demo跑不起来，npm start报错`(node:27352) UnhandledPromiseRejectionWarning: TypeError: html.replaceAll is not a function
    at D:\Code\MiniProgram-HotUpdate\脚手架\buildPage.js:252:33
    at String.replace (<anonymous>)
    at D:\Code\MiniProgram-HotUpdate\脚手架\buildPage.js:224:20
    at processTicksAndRejections (internal/process/task_queues.js:93:5)`
然后开发工具里的错`TypeError: onload1 is not a function
    at Ui.onLoad (index.js? [sm]:61)
    at Ui.<anonymous> (VM579 WAService.js:2)
    at Ui.l.__callPageLifeTime__ (VM579 WAService.js:2)
    at jt (VM579 WAService.js:2)`

**Comment by UncAnnyZ** [comment]
是不是没有安装插件

**Comment by 1977474741** [comment]
安装了的

**Comment by 1977474741** [comment]
安装了的

**Comment by UncAnnyZ** [comment]
我更新了一下demo和ast编译过程，你看看

**Comment by 1977474741** [comment]
拉了下重新install后npm run start还是报错，`> test@1.0.0 start D:\Code\MiniProgram-HotUpdate\脚手架
> node buildPage.js && webpack && node build.js && node run.js

D:\Code\MiniProgram-HotUpdate\脚手架\buildPage.js:18
  html = html.replaceAll(`"`, `'`)
              ^

TypeError: html.replaceAll is not a function
    at AstRead (D:\Code\MiniProgram-HotUpdate\脚手架\buildPage.js:18:15)
    at D:\Code\MiniProgram-HotUpdate\脚手架\buildPage.js:525:13
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61:3)`

**Comment by UncAnnyZ** [comment]
确保一下你node版本在16+嘛？
14的话会读取错误

**Comment by 1977474741** [comment]
版本是14，我升级试试

**Comment by 1977474741** [comment]
不支持标签指令吗？比如for，if

**Comment by UncAnnyZ** [comment]
支持
